// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'smartcampus-842a0',
    authDomain: 'smartcampus-842a0.firebaseapp.com',
    storageBucket: 'smartcampus-842a0.firebasestorage.app',
    measurementId: 'YOUR_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'smartcampus-842a0',
    storageBucket: 'smartcampus-842a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'smartcampus-842a0',
    storageBucket: 'smartcampus-842a0.firebasestorage.app',
    iosBundleId: 'com.example.smartcampus2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'smartcampus-842a0',
    storageBucket: 'smartcampus-842a0.firebasestorage.app',
    iosBundleId: 'com.example.smartcampus2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'smartcampus-842a0',
    authDomain: 'smartcampus-842a0.firebaseapp.com',
    storageBucket: 'smartcampus-842a0.firebasestorage.app',
    measurementId: 'YOUR_MEASUREMENT_ID',
  );
}