// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4_vzlZHL4Hv-sdNRsk-YesYnGiIOGmDc',
    appId: '1:988040395700:web:2d87339c50d3ba498950e1',
    messagingSenderId: '988040395700',
    projectId: 'smartcampus-97c86',
    authDomain: 'smartcampus-97c86.firebaseapp.com',
    storageBucket: 'smartcampus-97c86.firebasestorage.app',
    measurementId: 'G-MHX7PF5GT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOaDu4ySJT0N0Ets0e9rLF_Cmq9LOuo6I',
    appId: '1:988040395700:android:4e569e4901760d718950e1',
    messagingSenderId: '988040395700',
    projectId: 'smartcampus-97c86',
    storageBucket: 'smartcampus-97c86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOyH0IpDGvmfmTy3buwYdkTdI_3ZAXIRc',
    appId: '1:988040395700:ios:af39aab05b0963a08950e1',
    messagingSenderId: '988040395700',
    projectId: 'smartcampus-97c86',
    storageBucket: 'smartcampus-97c86.firebasestorage.app',
    iosBundleId: 'com.example.smartcampus2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOyH0IpDGvmfmTy3buwYdkTdI_3ZAXIRc',
    appId: '1:988040395700:ios:af39aab05b0963a08950e1',
    messagingSenderId: '988040395700',
    projectId: 'smartcampus-97c86',
    storageBucket: 'smartcampus-97c86.firebasestorage.app',
    iosBundleId: 'com.example.smartcampus2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4_vzlZHL4Hv-sdNRsk-YesYnGiIOGmDc',
    appId: '1:988040395700:web:e3e76a755532da988950e1',
    messagingSenderId: '988040395700',
    projectId: 'smartcampus-97c86',
    authDomain: 'smartcampus-97c86.firebaseapp.com',
    storageBucket: 'smartcampus-97c86.firebasestorage.app',
    measurementId: 'G-G80ERD3T6J',
  );

}